# Generated by Django 4.1.4 on 2022-12-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_produto_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='price',
            field=models.SmallIntegerField(default='0', verbose_name='Preço'),
        ),
    ]
