# Generated by Django 4.1.4 on 2022-12-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_produto_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='price',
            field=models.SmallIntegerField(default=0, verbose_name='Preço'),
        ),
    ]
