# Generated by Django 4.1.4 on 2022-12-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_produto_image_produto_imagemain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='price',
            field=models.FloatField(default=0, verbose_name='Preço'),
        ),
    ]
