# Generated by Django 4.1.4 on 2022-12-19 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_produto_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images', verbose_name='Imagem')),
                ('fk_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.produto')),
            ],
        ),
    ]
