# Generated by Django 4.1.4 on 2022-12-19 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_imagesproduto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesproduto',
            old_name='fk_produto',
            new_name='fkProduto',
        ),
    ]
