# Generated by Django 4.1.4 on 2023-01-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_imagesproduto_options_produto_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default='', max_length=3000, verbose_name='Descrição'),
        ),
    ]
